# Generated by Django 5.2.5 on 2025-08-15 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("reviewed", "Reviewed"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_pending", "Interview Pending"),
                    ("interview", "Interview"),
                    ("offered", "Offered"),
                    ("rejected", "Rejected"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                (
                    "scheduling_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_scheduled", models.BooleanField(default=False)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview",
                        to="core.application",
                    ),
                ),
            ],
        ),
    ]
